# Aliases used in the Collections docker container.

# Show the current folder in the prompt.
PS1='(debian)\w $ '

# Allow aliases to work with sudo, i.e.: "sudo ll".
alias sudo='sudo '

alias ls='ls --color=auto'
alias ll='ls -l'

alias g='gulp --silent'
alias gw='g watch &'
alias gr='g run-server &'
