# Aliases used in the Collections docker container.

# Show the current folder in the prompt.
PS1='(debian)\w $ '

# Allow aliases to work with sudo, i.e.: "sudo ll".
alias sudo='sudo '

alias ls='ls --color=auto'
alias ll='ls -l'

# Run jq to format and color json then pipe that to less.
# Use it as a pipe:  cat my.json | jqless
alias jqless='jq -C | less -R'

alias g='gulp'
alias gw='g watch &'
alias gr='g run-server &'

echo "Nginx now serving files on http://localhost:8000/index.html"
