# Aliases used in the Collections docker container.

# Show the platform and current folder in the prompt.
PS1='(debian)\w $ '

# Allow aliases to work with sudo, i.e.: "sudo ll".
alias sudo='sudo '

alias ls='ls --color=auto'
alias ll='ls -l'

# Run jq to format and color json then pipe that to less.
# Use it as a pipe:  cat my.json | jqless
alias jqless='jq -C | less -RF'

# Run the gulp command using the gulpfile in the tmp folder without
# changing the working directory.
alias g='gulp --cwd . --gulpfile tmp/gulpfile.js'

# Allow less to open compressed files as well as normal text files.
export LESSOPEN="| /usr/bin/lesspipe %s"
export LESSCLOSE="/usr/bin/lesspipe %s %s"

# Show the most recent files in a directory.
alias l=mylisttail
function mylisttail {
  dir=$1
  ls -ltr $dir | tail
}

# List directories.
alias lsd=mylistdir
function mylistdir {
  dir=$1
  if [ "$dir" == "" ] ; then
    dir='.'
  fi
  Blue='\033[1;34m'
  Cyan='\033[0;36m'
  NC='\033[0m'
  printf "$Blue"
  find $dir -maxdepth 1 -type d -printf "%p\n" | grep -v "^${dir}$" | sed "s@${dir}/@@"
  printf "$Cyan"
  find $dir -maxdepth 1 -type l -xtype d -printf "%p\n" | grep -v "^${dir}$" | sed "s@${dir}/@@"
  printf "$NC"
}

# Check that the configuration settings exist.

blueWarning="\033[34mWarning\033[0m"
if [[ ! -s "/home/coder/.aws" ]]; then
  echo
  echo -e "$blueWarning 1: aws command line credentials are missing."
  echo "Run: 'aws configure' to set them. See docs/aws-config.md for more info by"
  echo "running: glow docs/aws-config.md"
fi

if [[ ! -s "/home/coder/collections/env/aws-settings.json" ]]; then
  echo
  echo -e "$blueWarning 2: The aws-settings.json file is missing. Run: scripts/cognito -w"
  echo 'See docs/aws-config.md for more info by running: glow docs/aws-config.md'
fi

if [[ ! -s "/home/coder/collections/dist/index.html" ]]; then
  echo
  echo -e "$blueWarning 3: The website index.html file is missing. Run: g all"
  echo 'See docs/build.md for more info by running: glow docs/build.md'
else
  echo "Nginx now serving files. http://localhost:8000/index.html"
fi
