# Image-page SMS feedback. This file gets copied to ~/.aws/branding.ini in
# the docker container. The .aws file is not stored in git. Set admin_phone to
# your number, then run g all.
#
# admin_phone = "+1XXXXXXXXXX"

admin_phone =
feedback_message = "Image ${previewName}.  Hi Steve, \nI like this photo and "
