#!/bin/bash

# Create a zip file for the AWS lambda@edge authentication code for
# the validateImageRequest.js code.  This is needed for importing
# jsonwebtoken and other modules that don't come with the default
# runtime.
#
# This script follows the procedure documented here:
# https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html

# Specify the version of node js being used in the collection's
# container. In lambda specify the same version number.
#
# # in container
# node --version
#
# v18.19.0
version=18.19.0

# Make sure we're running inside the docker container.
if [[ -z "${coder_env}" ]]; then
  echo "Error: run in the docker container."
  exit
fi

jsFolder=~/collections/env/lambda/js

# If the package directory exists, delete it.
if [ -s "$jsFolder" ]; then
  echo "Remove existing $jsFolder directory"
  rm -rf $jsFolder
fi

mkdir -p $jsFolder
cd $jsFolder

handler=validateImageRequest.js
packFolder=package

echo "Copy $handler to the $jsFolder folder."
cp ~/collections/scripts/$handler $jsFolder/

echo "Install the dependent node modules."

# Create a package.json file containing the dependent modules.
# See env/debian/package.json for the version numbers.
cat > package.json << EOF
{
  "devDependencies": {
    "jsonwebtoken": "^9.0.2",
    "jwk-to-pem": "^2.0.7"
  }
}
EOF

# Install the dependent modules in the folder node_modules.
npm install

# For Lambda to run your code, the js file containing the handler
# code and all the function's dependencies must be installed at
# the root of the .zip file.

zipfile=lambda-js-$version.zip

echo "Create $zipfile."

zip -r $zipfile .

# Lambda@edge has a limit of 1 MB for the total size of the
# uncompressed zip files.  Here are the biggest files in the zip file:
#
# find env/lambda/js/ -printf "%s %f\n" | sort -n | tail
#
# ...
# 14924 range.js
# 15735 tests.js
# 16732 node.js
# 17008 hmac-drbg-nist.json
# 17709 README.md
# 18716 index.js
# 19555 README.md
# 22969 short.js
# 24425 README.md
# 32535 secp256k1.js
# 87731 bn.js
# 309174 lambda-js-18.19.0.zip
