#!/bin/bash

# Create a zip file for the AWS lambda@edge authentication code for
# the validateImageRequest.js code.  This is needed for importing
# jsonwebtoken and other modules that don't come with the default
# runtime.
#
# This script follows the procedure documented here:
# https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html

# Specify the version of node js being used in the collection's
# container. In lambda specify the same version number. Get the
# version with the -v option.

# # in container
# node -v
#
# v22.18.0
version=22.18.0

# Make sure we're running inside the docker container.
if [[ -z "${coder_env}" ]]; then
  echo "Error: run in the docker container."
  exit
fi

jsFolder=~/collections/env/lambda/js

# If the package directory exists, delete it.
if [ -s "$jsFolder" ]; then
  echo "Remove existing $jsFolder directory"
  rm -rf $jsFolder
fi

mkdir -p $jsFolder
cd $jsFolder

handler=validateImageRequest.js
packFolder=package

echo "Copy $handler to the $jsFolder folder."
cp ~/collections/scripts/$handler $jsFolder/

echo "Install the dependent node modules."

# Create a package.json file containing the dependent modules.
# See env/debian/package.json for the version numbers.
cat > package.json << EOF
{
  "devDependencies": {
    "jsonwebtoken": "^9.0.2",
    "jwk-to-pem": "^2.0.7"
  }
}
EOF

# Install the dependent modules in the folder node_modules.
npm install

# For Lambda to run your code, the js file containing the handler
# code and all the function's dependencies must be installed at
# the root of the .zip file.

zipfile=lambda-js-$version.zip

echo "Create $zipfile."

zip -r $zipfile .

maxzipsize=1048576
# maxzipsize=48576 # for testing

# Red Error.  Use with echo's -e option.
redError="\e[31mError\e[0m"

if [ $(stat -c %s "$zipfile") -lt $maxzipsize ]; then
  echo "Success: created zip file:"
  ls -l $zipfile
else
  echo

  find $jsFolder -printf "%s %f\n" | sort -n | tail -20

  echo
  echo -e "$redError: the zip file is too big."

cat << EOF
Lambda@edge has a limit of $maxzipsize for the total size of the
uncompressed zip file.  The list above shows the biggest files in
the js folder: $jsFolder
EOF

fi
