#!/bin/bash

# Create the main index page.
statictea -t templates/index.html -s collections.json -r index.html

# Create the thumbnails page.
statictea -t templates/thumbnails.html -s pages/collection-1.json -r pages/thumbnails-1.html

# Create the image page.
statictea -t templates/image.html \
  -s pages/collection-1.json \
  -r pages/image-1.html

