#!/bin/bash

echo "waiting for solution to timestamp issue. so only changed files are copied"
exit

# todo: share code between this script and save-images.

# Save the iphone images to the disk store.

SOURCE="$HOME/Pictures/Photos Library.photoslibrary/originals/"
DEST="/Volumes/home/pictures/iphone/"

# Make sure we're running on the host.
if [[ ! -z "${coder_env}" ]]; then
  echo "Error: run on the host."
  exit
fi

if [ ! -d "$SOURCE" ]; then
  echo "The source does not exist: $SOURCE"
  exit
fi

if [ ! -d "$DEST" ]; then
  echo "The destination does not exist: $DEST"
  exit
fi

# Note: we're using the a new version of rsync, not the mac version.
# Note: I turned on the rsync service on the network drive.
cmdPrefix="/opt/homebrew/bin/rsync -av --progress"

echo "Syncing iphone photos to the DiskStore."
echo "Running as user: $(whoami)"
echo "$cmdPrefix \"$SOURCE\" \"$DEST\""

$cmdPrefix "$SOURCE" "$DEST"

echo "done"
