#!/bin/bash

# Show the Cloudfront log fields of the last http request.

# Make sure we're running inside the docker container.
if [[ -z "${coder_env}" ]]; then
  echo "Error: run in the docker container."
  exit
fi

echo "Show the Cloudfront log fields of the last http request."
echo ""
echo "The cloudfront standard log reference:"
echo "https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/standard-logs-reference.html"
echo ""

echo "Number              Field  Value"
echo "------        -----------  ----------"

find logs/cloudfront -type f \
  | sort \
  | tail -1 \
  | xargs zcat \
  | awk '/^[0-9]/{for(i=1; i<=NF; i++) \
   {printf "%-4s %20s  %s\n", i, f[i], $i}; \
   {print "\n"};exit}\
   /#Fields: / {for(i=1; i<=NF; i++) {f[i] = $(i+1)}}'
