#!/bin/bash

# Show log information for a download.

# parameters: day and download id

# Make sure we're running inside the docker container.
if [[ -z "${coder_env}" ]]; then
  echo "Error: run in the docker container."
  exit
fi

day=$1
downloadId=$2

usage="Specify the day and download id, i.e.: scripts/view-logs 2025-02-05 UzCwQzMw"

if [ "$day" == "" ] || [ "${#day}" != "10" ]; then
  echo "$usage"
  echo "day: ${day}"
  echo "day length: ${#day}"
  exit
fi
if [ "$downloadId" == "" ] || [ "${#downloadId}" != "8" ] ; then
  echo "$usage"
  echo "download id: ${downloadId}"
  echo "download id length: ${#downloadId}"
  exit
fi

# echo "day: ${day}"
# echo "download id: ${downloadId}"

# Example lambda logs:
#
# 2025-02-07T01:44:09.064Z START RequestId: 57f7dfb5-e844-469d-b615-b5b8202efbc4 Version: 28
#
# 2025-02-07T01:44:09.178Z 2025-02-07T01:44:09.178Z	57f7dfb5-e844-469d-b615-b5b8202efbc4	INFO	Trying: 100 / undefined
#
# 2025-02-07T01:44:09.198Z REPORT RequestId: 57f7dfb5-e844-469d-b615-b5b8202efbc4	Duration: 134.17 ms	Billed Duration: 135 ms	Memory Size: 128 MB	Max Memory Used: 80 MB
#
# 2025-02-07T01:42:25.138Z END RequestId: 21cebdaa-57e1-4f31-844f-013f7b8ffe96

find logs/cloudfront -type f \
  | xargs zcat \
  | grep $downloadId \
  | awk 'BEGIN {n = split("3 4 5 11 14 21 31 10", \
    list, " ") } \
    /^[0-9]/ {for(i=1; i<=n; i++) \
    {$14=substr($14,0,11); printf "%s ", $list[i]}; print ""}' \
  | sort

find logs/lambda -type f \
  | grep "$day" \
  > lambda-files.txt

if [ ! -s "lambda-files.txt" ]; then
  echo "No lambda log files found with that day."
  exit
fi

# Create the requests-lines.txt file that contains the request ids of
# all the lines associated with the download id.
cat lambda-files.txt \
  | xargs zgrep "$downloadId" \
  | grep -Eo '[[:xdigit:]]{8}-([[:xdigit:]]{4}-){3}[[:xdigit:]]{12}' \
  | sort | uniq \
  > requests-lines.txt

if [ ! -s "requests-lines.txt" ]; then
  echo "No lambda log files found with that download id."
  exit
fi

# Show the lines that match the request line ids. Sort by the order the
# requests come in then by time so each request's lines are next to
# each other.
cat lambda-files.txt \
  | xargs zcat \
  | grep -F -f requests-lines.txt \
  | awk '\
    / START RequestId: / \
      {id = substr($4, 0, 8); \
      if (!(id in ids)) { ids[id] = NR};
      printf "%4s %s %s %s\n", \
      ids[id], substr($1, 0, 10), substr($1, 12, 12), id; \
      printf "%4s %s %s %s ", \
      ids[id], substr($1, 0, 10), substr($1, 12, 12), id; print $5, $6} \
    /INFO/ \
      {id = substr($3, 0, 8); \
      if (!(id in ids)) { ids[id] = NR};
      printf "%4s %s %s %s ", \
      ids[id], substr($1, 0, 10), substr($1, 12, 12), id; \
      for (i = 5; i <= NF; i++) printf "%s ", $i; print ""} \
    / REPORT RequestId: / \
      {id = substr($4, 0, 8); \
      if (!(id in ids)) { ids[id] = NR};
      printf "%4s %s %s %s ", \
      ids[id], substr($1, 0, 10), substr($1, 12, 12), id; \
      printf "%s %s\n", $6, $7} \
    ' \
  | sort -k1,1n -k3,3 \
  | awk '{for (i = 2; i <= NF; i++) printf "%s ", $i; print ""}'

rm -f requests-lines.txt
rm -f lambda-files.txt
