#!/bin/bash

# Show cloudfront log requests.

# Make sure we're running inside the docker container.
if [[ -z "${coder_env}" ]]; then
  echo "Error: run in the docker container."
  exit
fi

find logs/cloudfront -type f \
  | xargs zcat \
  | awk '/^[0-9]/ {id=substr($14,4,8); if (id == "") id="-"; \
     user=substr($14,18,8); if (user == "") user="-";\
     rid = substr($17, 0, 8); hit = substr($31, 0, 10); \
     printf "%s %s %9s %s %8s %8s %8s %10s %s %s\n", \
     $3, $4, $5, $11, id, user, rid, hit, $21, $10}' \
  | sort
# 3, 4, 5, 11, 14, 14, 17, 31, 21, 10
