#!/bin/bash

# Show log information for a download.

# parameters: day and download id

# Make sure we're running inside the docker container.
if [[ -z "${coder_env}" ]]; then
  echo "Error: run in the docker container."
  exit
fi

day=$1
downloadId=$2

usage="Specify the day and download id, i.e.: scripts/viewlogs 2025-02-05 UzCwQzMw"

if [ "$day" == "" ] || [ "${#day}" != "10" ]; then
  echo "$usage"
  echo "day: ${day}"
  echo "day length: ${#day}"
  exit
fi
if [ "$downloadId" == "" ] || [ "${#downloadId}" != "8" ] ; then
  echo "$usage"
  echo "download id: ${downloadId}"
  echo "download id length: ${#downloadId}"
  exit
fi

# echo "day: ${day}"
# echo "download id: ${downloadId}"

# Example lambda logs:
#
# 2025-02-07T01:44:09.064Z START RequestId: 57f7dfb5-e844-469d-b615-b5b8202efbc4 Version: 28
#
# 2025-02-07T01:44:09.178Z 2025-02-07T01:44:09.178Z	57f7dfb5-e844-469d-b615-b5b8202efbc4	INFO	Trying: 100 / undefined
#
# 2025-02-07T01:44:09.198Z REPORT RequestId: 57f7dfb5-e844-469d-b615-b5b8202efbc4	Duration: 134.17 ms	Billed Duration: 135 ms	Memory Size: 128 MB	Max Memory Used: 80 MB
#
# 2025-02-07T01:42:25.138Z END RequestId: 21cebdaa-57e1-4f31-844f-013f7b8ffe96


# Create the requests-lines.txt file that contains the request ids of
# all the lines associated with the download id.
find logs/lambda -type f \
  | grep "$day" \
  | xargs zcat \
  | grep "$downloadId" \
  | awk '{print $3}' \
  | sort | uniq \
  > requests-lines.txt

if [ ! -s "requests-lines.txt" ]; then
  echo "No log files found with that day and download id."
  exit
fi

# Show the lines that match the request line ids.
find logs/lambda -type f \
  | grep "$day" \
  | xargs zcat \
  | grep -F -f requests-lines.txt \
  | awk '\
    / START RequestId: / \
      {printf "%s %s %s ", \
      substr($1, 0, 10), substr($1, 12, 12), substr($4, 0, 8); print "-----", $5, $6} \
    /INFO/ \
      {printf "%s %s %s ", \
      substr($1, 0, 10), substr($1, 12, 12), substr($3, 0, 8); \
      for (i = 5; i <= NF; i++) printf "%s ", $i; print ""} \
    / REPORT RequestId: / \
      {printf "%s %s %s ", \
      substr($1, 0, 10), substr($1, 12, 12), substr($4, 0, 8); \
      print $6, $7} \
    '

rm -f requests-lines.txt
